services:
  - type: web
    name: rutland-pos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        value: rutland_secret_key_8583
      - key: FLASK_ENV
        value: production

